// Code generated by MockGen. DO NOT EDIT.
// Source: src/service/calculate_service.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCalculateService is a mock of CalculateService interface.
type MockCalculateService struct {
	ctrl     *gomock.Controller
	recorder *MockCalculateServiceMockRecorder
}

// MockCalculateServiceMockRecorder is the mock recorder for MockCalculateService.
type MockCalculateServiceMockRecorder struct {
	mock *MockCalculateService
}

// NewMockCalculateService creates a new mock instance.
func NewMockCalculateService(ctrl *gomock.Controller) *MockCalculateService {
	mock := &MockCalculateService{ctrl: ctrl}
	mock.recorder = &MockCalculateServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCalculateService) EXPECT() *MockCalculateServiceMockRecorder {
	return m.recorder
}

// Service mocks base method.
func (m *MockCalculateService) Service(loopNumber int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Service", loopNumber)
	ret0, _ := ret[0].(int)
	return ret0
}

// Service indicates an expected call of Service.
func (mr *MockCalculateServiceMockRecorder) Service(loopNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Service", reflect.TypeOf((*MockCalculateService)(nil).Service), loopNumber)
}
